name: Package and release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - "*"
    paths-ignore:
      - ".github/**"

env:
  GITHUB_OAUTH: ${{ secrets.RELEASETOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # gets entire git history, needed for automatic changelogs

      - name: Package and release
        uses: BigWigsMods/packager@v2
